# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pId', models.CharField(max_length=100)),
                ('pName', models.CharField(max_length=20)),
                ('pDescribe', models.CharField(max_length=50)),
                ('pIconPath', models.CharField(max_length=100)),
            ],
        ),
    ]
