# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170412_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
